/*
PREGUNTAS Y COSAS QUE NO SE!!!


CLIENTE CRISTOFY
- Como puedo pasar el socket del login a la ventana cliente?
para seguir teniendo la conexion en la sigueinte ventana

- los datos se pasan igual que los strings? el array de canciones??
  no hay que hacer nada mas? wayy, pues si ke hay ke hacerlo diferenete

- se trabaja siempre con el mismo socket.. no? o si cambio de ventana, y voy a pedir otro tipo de cosas, se crea otro socket???


SERVIDOR CRISTOFY
- del servidor, que pongo en el boton desconectar? ke es desconectar?
    serversocket.close();
- no he hecho ningun join de las hebras... nose donde ni como


GENERALES
-como se hace un ejecutable para windows? ke funcione aunke no tenga instalado java development, la makina virtual si, claro.. o no.





*/




package Vista;

import Controlador.SocketCliente;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JuanPablo
 */
public class Login extends javax.swing.JFrame {

    //variable que cambiaremos a true si la conexion ha ido bien, y si las credenciales de user y password son correctas
    boolean resultado;
    
    String[] args;
   
    //el puerto de conexion, cambiar aki si ha de cambiar
    //final int PUERTO = 5000;
    
    String ip;
    String login;
    String pass;
    int puerto;
    
    String protocolo;
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textIp = new javax.swing.JTextField();
        botonConectar = new javax.swing.JButton();
        textPassword = new javax.swing.JPasswordField();
        textIncorrecto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textPuerto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 68, -1, -1));

        jLabel3.setText("Ip");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 27, 107, -1));

        textIp.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textIp.setText("127.0.0.1");
        textIp.setToolTipText("");
        getContentPane().add(textIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 107, -1));

        botonConectar.setText("Conectar");
        botonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        textPassword.setToolTipText("");
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 65, 107, -1));

        textIncorrecto.setForeground(new java.awt.Color(255, 0, 0));
        textIncorrecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textIncorrecto.setToolTipText("");
        getContentPane().add(textIncorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 207, 23));

        jLabel4.setText("Puerto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        textPuerto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textPuerto.setText("5000");
        textPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPuertoActionPerformed(evt);
            }
        });
        getContentPane().add(textPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 107, -1));

        jLabel5.setText("Parámetros conexión con el servidor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CrstofyLogo150px.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 530, 270));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/jesusDance.gif"))); // NOI18N
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 270, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarActionPerformed
        
        //pongo la variable a false siempre al entrar
        resultado = false;
        
        //ahora cogemos la ip introducida en el formulario y la pasamos a la variable
        ip = textIp.getText();
        //lo mismo con las demás
        login = textUsuario.getText();
        pass = textPassword.getText();
        puerto = Integer.parseInt(textPuerto.getText());
        
        
        //llamo a la clase socket cliente, y a sus metodos para hacer el socket
        //y para comprobar protocolos
        SocketCliente sc = new SocketCliente(ip, puerto);
       
        try {
            resultado = sc.comprobarProtocoloLogin(login, pass);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        //Si es true, es que la comprobacion ha sido exitosa
        if(resultado){
            
            //aki se cierra la ventana actual, y se abre la ventana CLIENTE
            this.dispose();
           
            //le paso por parametros al constructor la ip y el user y SOCKET
            Cliente cli = new Cliente(textIp.getText(), textUsuario.getText(), sc );
            cli.setVisible(true);
            
           
        }else{
            textIncorrecto.setText("Usuario o contraseña incorrectos");
            
        }
    }//GEN-LAST:event_botonConectarActionPerformed

    private void textPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPuertoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel textIncorrecto;
    private javax.swing.JTextField textIp;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textPuerto;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
